apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/climacs-net/helm-charts' #https://github.com/climacs-net/my-cool-services/tree/main/helm-charts
    targetRevision: HEAD
    path: my-cool-service
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
