apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-cool-service-ingress
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt"
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  rules:
    - host: "malamig-na-serbisyo.climacs.net"
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: my-cool-service
                port:
                  number: 8000
  tls:
    - hosts:
        - "malamig-na-serbisyo.climacs.net"
      secretName: my-cool-service-tls
