apiVersion: v1
kind: Service
metadata:
  name: my-cool-service
spec:
  type: {{ .Values.service.type }}
  selector:
    app: my-cool-service
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
