apiVersion: v1
kind: Service
metadata:
  name: opa-service
spec:
  type: {{ .Values.service.type }}
  selector:
    app: opa-service
  ports:
    - protocol: TCP
      port: 8181
      targetPort: 8181
